Fix getenv
We were importing different versions of getenv in react-native/
and desktop/.  Webpack was choosing the older react-native one
and ignoring the desktop one, leading to:

TypeError: _getenv2.default.boolish is not a function

While we're at it, move to the latest upstream version which has
incorporated @chrisnojima's addition of boolish.