vendor: update go-git to fix corrupt ref issue
A user hit the following scenario:
* Started pushing a new git branch.
* Wrote all git objects successfully to the journal.
* Open the ref filename with O_CREATE, creating the file in the local
  journal.
* Attempt to take the lock on the file.
* A flaky network failed the Lock command (or possibly the later
  Close/Unlock command), causing the `setRef` call to return an error.
* This fails that one specific ref push, but git has independent
  errors for each ref, so it doesn't fail the whole git operation.
* The kbfsgit runner then tries to sync the whole journal, and
  succeeds eventually, which pushes the still-empty ref file to the
  main repo.
* Later when the user tries to pull from the repo, they see an error:

```
fatal: bad object 0000000000000000000000000000000000000000
error: keybase://team/teamname/reponame did not send all necessary objects
```

This fix in the go-git repo attempts to prevent this from happening by
reverting files in the local journal to their original state if the
`setRef` operation fails.  In the example above, it would have meant
that the ref file was deleted and never pushed to the server (though
all the object files still would have been synced correctly).

Issue: KBFS-3703